# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fizzbuzz.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.CalcFizzBuzzRequest" do
    optional :num, :int64, 1
  end
  add_message "proto.CalcFizzBuzzReply" do
    optional :res, :string, 1
  end
end

module Proto
  CalcFizzBuzzRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CalcFizzBuzzRequest").msgclass
  CalcFizzBuzzReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CalcFizzBuzzReply").msgclass
end
