# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: fizzbuzz.proto for package 'proto'

require 'grpc'
require 'fizzbuzz_pb'

module Proto
  module FizzBuzz
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.FizzBuzz'

      rpc :CalcFizzBuzz, CalcFizzBuzzRequest, CalcFizzBuzzReply
    end

    Stub = Service.rpc_stub_class
  end
end
