version: "3"
services:
  web:
    build: web
  rtmp:
    build: nginx-rtmp
    ports:
      - "1935:1935"
      - "8081:8081"
      - "8080:8080"
    links:
      - web
  chat:
    build: chat
    ports:
      - "8082:8080"
    links:
      - redis
  redis:
    image: redis
